INSERT INTO BUILDING(ID, NAME)
VALUES (1, 'DZIALOWNIA');
INSERT INTO BUILDING(ID, NAME)
VALUES (2, 'PODCHORAZYCH');
INSERT INTO BUILDING(ID, NAME)
VALUES (3, 'CHEMICZNY');


INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (1, '1/15', 1);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (2, '150', 3);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (3, '151', 3);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (4, '143', 3);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (5, '142', 3);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (6, '135', 3);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (7, '136', 3);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (8, 'F112', 2);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (9, 'F201', 2);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (10, 'F203', 2);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (11, 'F020', 2);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (12, 'F015', 2);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (13, 'F202', 2);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (14, 'F205', 2);
INSERT INTO AUDITORIUM(ID, NAME, BUILDING_ID)
VALUES (15, 'F003', 2);